name: gh-pages
on:
  push:
    branches: [ "main" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get Version
        id: get
        run: echo "::set-output name=ver::$(git submodule status)"
        shell: bash
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: mathjax-src/es5
          key: id-${{ steps.get.outputs.ver }}
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Mathjax
        run: |
          mkdir ./public
          npm install mathjax@3
          mv node_modules/mathjax/es5 ./public/mathjax-src
      - name: Packing
        run: |
          cp ./MathJax-v3-and-Marked.html ./public
          mkdir -p ./public/marked
          cp ./marked/marked.min.js ./public/marked/marked.min.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
