name: gh-pages
on:
  push:
    branches: [ "main" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get Version
        id: get
        run: git submodule status>substat.txt
        shell: bash
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: mathjax-src/es5
          key: id-${{ hashFiles('substat.txt') }}
      - name: Setup
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: mathjax-src
        run: npm install
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: mathjax-src
        run: npm run compile
      - name: Components
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: mathjax-src/components
        run: ./bin/makeAll
      - name: Packing
        run: |
          mkdir public
          cp MathJax-v3-and-Marked.html public
          mkdir -p public/mathjax-src/es5
          cp mathjax-src/es5/tex-mml-chtml.js public/mathjax-src/es5/tex-mml-chtml.js
          mkdir -p public/marked
          cp marked/marked.min.js public/marked/marked.min.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
